# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "The Language of Music"
license = "Amanda"
licenselink = "https://github.com/amandasommer/music.github.io/blob/main/LICENSE.md"
description = "testing"
homepage = "https://amandasommer.github.io/music.github.io/"
tags = ["website", "starter", "responsive", "Disqus", "blog", "Tachyons", "Multilingual", "Stackbit"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.64.0"

[author]
  name = "AmandaSommer"
  homepage = "https://amandasommer.github.io/music.github.io/"
